## This Workflow runs when code is pushed into the Develop or PROD branches.
## This ensures Workbench has up-to-date reports for these branches.
name: Update Main Branch Scan

on: 
  push:
    branches:
    - 'develop'
    - 'PROD'
      
jobs:
  fossid_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Code; Ignoring File Types
        run: |
          zip -r $GITHUB_WORKSPACE/code.zip . -x \
          '*.tmp' '*.temp' '*.bak' \
          '*.cache' '*.db' '*.idx' \
          '*.log' '*.txt' '*.event' \
          '*.sample' '*.demo' '*.example' \
          '*.sql' '*.hprof' '*.dmp' \
          '.gitignore' '.dockerignore' '.snyk' \
          '.git/*' '.github/*'

      #- name: Authenticate to Quay
      #  uses: docker/login-action@v2
      #  with:
      #    registry: quay.io/fossid
      #    username: ${{ secrets.QUAY_USER }}
      #    password: ${{ secrets.QUAY_TOKEN }}

      #- name: Run Workbench Agent
      #  run: |
      #    docker run -v ${{ github.workspace }}:/tmp/scan_target \
      #               quay.io/fossid/workbench-agent:0.7.0 \
      #      --api_url ${{ secrets.WORKBENCH_URL }} \
      #      --api_user ${{ secrets.WORKBENCH_USER }} \
      #      --api_token ${{ secrets.WORKBENCH_TOKEN }} \
      #      --project_code $GITHUB_REPOSITORY \
      #      --scan_code $GITHUB_REPOSITORY/$GITHUB_REF_NAME \
      #      --path /tmp/scan_target/code.zip \
      #      --chunked_upload \
      #      --auto_identification_detect_declaration \
      #      --auto_identification_detect_copyright \
      #      --auto_identification_resolve_pending_ids \
      #      --run_dependency_analysis \
      #      --delta_only

      - name: Checkout FossID Workbench Agent Repo
        uses: actions/checkout@v4
        with: 
          repository: fossid-ab/workbench-agent
          path: fossid-tools

      - name: Prepare Workbench Agent
        run: pip install -r fossid-tools/requirements.txt

      ## For the Develop and Main Branches, we run License Extraction.
      ## This ensures SBOMs contain file-level licenses and copyrights.
      - name: Run Workbench Agent
        run: |
          python fossid-tools/workbench-agent.py \
            --api_url ${{ secrets.WORKBENCH_URL }} \
            --api_user ${{ secrets.WORKBENCH_USER }} \
            --api_token ${{ secrets.WORKBENCH_TOKEN }} \
            --project_code $GITHUB_REPOSITORY \
            --scan_code $GITHUB_REPOSITORY/$GITHUB_REF_NAME \
            --path $GITHUB_WORKSPACE/code.zip \
            --chunked_upload \
            --auto_identification_resolve_pending_ids \
            --auto_identification_detect_declaration \
            --auto_identification_detect_copyright \
            --run_dependency_analysis \
            --delta_only 
