## This Workflow runs when code is pushed into the Develop or PROD branches.
## This ensures Workbench has up-to-date reports for these branches.
name: Update Main Branch Scan

on: 
  push:
    branches:
    - 'develop'
    - 'PROD'
      
jobs:
  fossid_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Code; Ignoring File Types
        run: |
          zip -r $GITHUB_WORKSPACE/code.zip . -x \
          '*.tmp' '*.temp' '*.bak' \
          '*.cache' '*.db' '*.idx' \
          '*.log' '*.txt' '*.event' \
          '*.sample' '*.demo' '*.example' \
          '*.sql' '*.hprof' '*.dmp' \
          '.gitignore' '.dockerignore' '.snyk' \
          '.git/*' '.github/*'

      - name: Checkout FossID Workbench Agent Repo
        uses: actions/checkout@v4
        with: 
          repository: fossid-ab/workbench-agent
          path: fossid-tools

      - name: Prepare Workbench Agent
        run: pip install -r fossid-tools/requirements.txt

      ## For the Develop and Main Branches, we run License Extraction.
      ## This ensures SBOMs contain file-level licenses and copyrights.
      - name: Run Workbench Agent
        run: |
          python fossid-tools/workbench-agent.py \
            --api_url ${{ secrets.WORKBENCH_URL }} \
            --api_user ${{ secrets.WORKBENCH_USER }} \
            --api_token ${{ secrets.WORKBENCH_TOKEN }} \
            --project_code $GITHUB_REPOSITORY \
            --scan_code $GITHUB_REPOSITORY/$GITHUB_REF_NAME \
            --path $GITHUB_WORKSPACE/code.zip \
            --auto_identification_resolve_pending_ids \
            --auto_identification_detect_declaration \
            --auto_identification_detect_copyright \
            --run_dependency_analysis \
            --delta_only 