## This workflow runs when a PR is opened to PROD.
name: Checks on PR to PROD

on:
  pull_request:
    branches: [ PROD ]
    
## This job checks that the HEAD branch does not introduce risks into PROD.    
jobs:
  evaluate_fossid_gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FossID Scripts Repo
        uses: actions/checkout@v4
        with: 
          repository: fossid-ab/workbench-api-samples

      - name: Evaluate Post Scan Gates
        run: |
          python post-scan-gates/post_scan_gates.py \
          --workbench-url ${{ secrets.WORKBENCH_URL }} \
          --workbench-user ${{ secrets.WORKBENCH_USER }} \
          --workbench-token ${{ secrets.WORKBENCH_TOKEN }} \
          --scan-code $GITHUB_REPOSITORY/$GITHUB_HEAD_REF \
          --policy-check