## This workflow runs when a PR is opened to PROD.
name: Checks on PR to PROD

on:
  pull_request:
    branches: [ PROD ]
    
## This job checks that the HEAD branch does not introduce risks into PROD.    
jobs:
  workbench-gates:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}
    steps:
      - name: Evaluate Gates
        run: |
          docker run --rm \
            ghcr.io/tomgonzo/workbench-cli:latest \
            --api-url ${{ env.WORKBENCH_URL }} \
            --api-user ${{ env.WORKBENCH_USER }} \
            --api-token ${{ env.WORKBENCH_TOKEN }} \
            evaluate-gates \
            --project-name $GITHUB_REPOSITORY \
            --scan-name $GITHUB_HEAD_REF \
            --fail-on-pending \
            --fail-on-policy